Absence/urls.py
from django.urls import re_path
from Absence import views

urlpatterns = [
    re_path('^$', views.Front_page , name='Front_Page'),
    re_path('Acceuil/', views.Acceuil , name='Acceuil'),
    re_path('Register/', views.Register , name ='register'),
    re_path('Emploi/', views.Emploi , name ='Emploi'),
    re_path('Check/',views.Check_salle, name='EMp'),
    re_path('submission/', views.submit_to_database , name ='Emploi'),
    re_path('emploi_template/',views.Emploi_template,name='emploi_template'),

]




 

Bachlor_App/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Absence.urls')),    

]

Absence/models.py
from django.db import models

# Creaste your models here.
class Students(models.Model):
	dict ={
	       'Nom':'',
		   'Prenom':'',
		   'Sexe':'',
		   'Adresse':'',
		   'Telephone':'',
		   'Email':'',
		   'filliere':'',
		   'Semestre':''
	}
	Nom = models.CharField(max_length = 250)
	Prenom =  models.CharField(max_length = 250)
	Sexe=models.CharField(max_length = 250)
	Adresse= models.CharField(max_length = 250, default='null')
	Telephone= models.CharField(null = True , max_length = 250)
	Email= models.EmailField(blank = True)	
	filliere = models.CharField(max_length = 250 ,default='null')
	Semestre = models.CharField(max_length = 250 ,default='null')
	def __str__(self):
		return self.Nom+'-'+self.Prenom +'('+self.filliere+')' 
class salle(models.Model):
		numero = models.IntegerField()
		def __str__(self):
			return  'Salle :'+str(self.numero)
class Horaire(models.Model):
	    horaire = models.CharField(max_length=250)
	    def __str__(self):
	    	return  str(self.horaire)
class Jour(models.Model):
		nom_Jour = models.CharField(max_length = 250)
		def __str__(self):
	        	return str(self.nom_Jour)
class Crenau(models.Model):
	    horaire =models.ForeignKey(Horaire,on_delete=models.CASCADE ,default=None, null=True)
	    salle = models.ForeignKey(salle,on_delete=models.CASCADE,default=None, null=True)
	    Jour= models.ForeignKey(Jour,on_delete=models.CASCADE,default=None, null=True)
	    Matiere = models.CharField(max_length = 250 , default='null')
	    Professeur = models.CharField(max_length = 250,default='null')
	    def __str__(self):
	        	return str(self.horaire)+'-'+str(self.Jour)
class Admin(models.Model):
		email = models.CharField(max_length=250)
		password = models.CharField(max_length=250)
		def __str__(self):
				return str(self.email)
		
		

Absence/forms.py
from django import forms
from .models import *

class NameForm(forms.ModelForm):
		Matiere = forms.CharField(max_length = 250 )
		Professeur = forms.CharField(max_length = 250 )
		Jour = forms.ModelChoiceField(queryset = Jour.objects.all())
		salle = forms.ModelChoiceField(queryset = salle.objects.all())
		horaire = forms.ModelChoiceField(queryset = Horaire.objects.all())
		class Meta:
			model = Crenau
			fields = ('Jour','salle','horaire','Professeur','Matiere',)


	
			

Absence/microblog/app/routes.py
from app import app

@app.route('/')
@app.route('/index')
def index():
    return "Hello, World!"

Absence/views.py
from django.shortcuts import render
from django.http  import HttpResponse
from django.template import loader
from .models import *
from Absence.forms import *
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.core import serializers
from django.http.response import HttpResponseRedirect
from django.contrib import messages 
from django.views.generic import View
from django.template.loader import get_template


def Front_page(resquest):
    template = loader.get_template('Login.html')
    context = {
    }
    return HttpResponse(template.render(context,resquest))
def Acceuil(resquest):
    email = str(resquest.POST.get('email', None))
    password = str(resquest.POST.get('password',None))
    admins = Admin.objects.all()
    for admin in admins:
        if admin.email == email and admin.password == password:
            all_students = Students.objects.all()
            template = loader.get_template('Front_page.html')
            context = {
            'all_students' :all_students,  
            }
            return HttpResponse(template.render(context,resquest))
        else :
            template = loader.get_template('Login.html')
            context = {
            }
            return HttpResponse(template.render(context,resquest))
def Charts(resquest):
    all_students = Students.objects.all()
    template = loader.get_template('Charts.html')
    context ={
    'all_students' :all_students,  
    }
    return HttpResponse(template.render(context,resquest))

def Tables(resquest):
    all_students = Students.objects.all()
    template = loader.get_template('tables.html')
    context ={
    'all_students' :all_students,  
    }
    return HttpResponse(template.render(context,resquest))    

def Register(resquest):
    template = loader.get_template('register.html')
    context = {
    }
    return HttpResponse(template.render(context,resquest))
def  Emploi (resquest):
    all_salles = salle.objects.all()
    all_horaires = Horaire.objects.all()
    Jours = Jour.objects.all()
    template = loader.get_template('Emploi.html')
    context ={'all_salles': all_salles,'all_horaires':all_horaires,'Jours' : Jours,}
    return render(resquest,'Emploi.html',context)
def Check_salle(resquest):
        jour = str(resquest.GET.get('Jour', None))
        Horaire = str(resquest.GET.get('Horaire', None))
        Salle_choisie = str(resquest.GET.get('Salle_choisie',None))
        all_salles = salle.objects.all()
        all_crenau = Crenau.objects.all()
        for Crenaus in all_crenau :
         if(str(Crenaus.Jour.id)==jour and str(Crenaus.horaire.id)==Horaire):
           all_salles = all_salles.exclude(numero=Crenaus.salle.numero)  
        data ={
            'is_not_taken':all_salles.filter(id=Salle_choisie).exists()
        }          
        return JsonResponse(data)
def submit_to_database(request):
    template = loader.get_template('template2.html')
    if request.method == 'POST':
        Professeur = str(request.POST.get('Prof',False))
        Matiere = str(request.POST.get('matière',False))
        jour = request.POST.get('jour',False)
        Salle = request.POST.get('salle',False)
        horaire = request.POST.get('horaire',False)
        form=NameForm({'Matiere':Matiere , 'Professeur' :Professeur ,'salle':Salle ,'horaire' :horaire ,'Jour' : jour })
        if form.is_valid():       
           form.save()  
    jours = Jour.objects.all()
    Horaires = Horaire.objects.all()
    all_salles = salle.objects.all()
    Crenaus = Crenau.objects.all()
    context = {
    'Jours' : jours,
    'Horaires': Horaires,
    'Crenaus': Crenaus,
    'all_horaires':Horaires,
    'all_salles': all_salles,
    }  
    return HttpResponse(template.render(context,request))
def Emploi_template(request):
    template = loader.get_template('template2.html')
    jours = Jour.objects.all()
    Horaires = Horaire.objects.all()
    Crenaus = Crenau.objects.all()
    all_salles = salle.objects.all()
    for creno in Crenaus:
        print(creno)
    context = {
    'Jours' : jours,
    'Horaires': Horaires,
    'Crenaus': Crenaus,
    'all_horaires':Horaires,
    'all_salles': all_salles,
    }
    return HttpResponse(template.render(context,request)) 

Absence/templates/Emploi.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="no-js" >
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Blank Page</title>
    <!-- Bootstrap core CSS-->
    <link href="{% static "css_emploi/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static "css_emploi/all.min.css" %}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="{% static "css_emploi/dataTables.bootstrap4.css" %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static "css_emploi/sb-admin.css" %}" rel="stylesheet">

  </head>
  <body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
      <a class="navbar-brand mr-1" href="index.html">Start Bootstrap</a>
      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>
      <!-- Navbar Search -->
      <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>
      <!-- Navbar -->
   
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <span class="badge badge-danger">9+</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>

          </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <span class="badge badge-danger">7</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="#">Activity Log</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul>
    </nav>
    <div id="wrapper">
      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="pagesDropdown">
            <h6 class="dropdown-header">Login Screens:</h6>
            <a class="dropdown-item" href="login.html">Login</a>
            <a class="dropdown-item" href="register.html">Register</a>
            <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Other Pages:</h6>
            <a class="dropdown-item" href="404.html">404 Page</a>
            <a class="dropdown-item active" href="blank.html">Blank Page</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
        </li>
      </ul>
      <div id="content-wrapper">
        <div class="container-fluid">
          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="index.html">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Blank Page</li>
          </ol>
          <!-- Page Content -->
        <form class="contact-form" action="/submission/" method="post">
          {% csrf_token %}
           <div class="form-group">
             <label>Jour :</label>
             <select class="custom-select"  name="jour" id="id_jour" >
                <option  selected  >Choisir votre Jour</option>
                {% for jour in Jours %}
                <option value={{ jour.id }}  > {{ jour.nom_Jour }}</option>
                {%endfor%}
            </select>           
           </div>
           <div class="form-group" id="WHT">
            <label>Horaire :</label>
            <select class="custom-select"  name="horaire" id="id_horaire" >
                <option  selected  >Choisir votre crenau</option>
                {% for horaire in all_horaires %}
                <option value={{ horaire.id }}  > {{ horaire.horaire }}</option>
                {%endfor%}
            </select>
           </div>
           <div class="form-group">
             <label>La salle :</label>
             <select class="custom-select"  name="salle" id="id_salles">
                <option selected>Choisir votre Salle</option>
                {% for salleu in all_salles %}
                <option value={{ salleu.id }}>{{ salleu.numero }}</option>
                {% endfor %}
             </select>
           </div>           
           <div class="form-group">
             <label>Le professeur :</label>
             <input type="text" class="form-control" name="Prof" placeholder="Entrez le professeur...">
           </div>
           <div class="form-group">
             <label>La matière :</label>
             <input type="text" class="form-control" name="matière"placeholder="Entrez la matière...">
           </div>
                  <button type="submit" class="btn btn-primary">Ajouter</button>
        </form>         
        <!-- /.container-fluid -->
        <!-- Sticky Footer -->
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span> Copyright © Team Bachelor </span>
            </div>
          </div>
        </footer>
      </div>
      <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src=" {% static "js_emploi/jquery.min.js" %}"></script>
    <script src=" {% static "js_emploi/bootstrap.bundle.min.js" %}"></script>
    <!-- Core plugin JavaScript-->
    <script src=" {% static  "js_emploi/jquery.easing.min.js"%}"></script>
    <!-- Custom scripts for all pages-->
    <script src=" {% static  "js_emploi/sb-admin.min.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
      
  </body>
</html>

Absence/templates/template2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600" rel="stylesheet">
    <title>SB Admin - Blank Page</title>
    <!-- Bootstrap core CSS-->
    <link href="{% static "css_emploi/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static "css_emploi/all.min.css" %}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="{% static "css_emploi/dataTables.bootstrap4.css" %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static "css_emploi/sb-admin.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "schedule-template-master/css/reset.css" %}"> 
    <link href="{% static "css_emploi/styleS.css" %}" rel="stylesheet">
    <style type="text/css">
         ODY {
          font-family: Trebuchet MS;
          margin:20px;
          background-color: #600040;
        }

        H1 {
          text-align: center;
          padding-bottom: 30px;
          color: #000000
        }

        .myTimetable {
          width:100%;
          border-collapse: collapse;
          table-layout: fixed;
        }

        .myTimetable THEAD{
          color: #000000;
        }
        .myTimetable TH {
          border: 1px solid black;
          padding: 6px;
          text-align: center
        }
        .myTimetable TBODY {
          background-color: #C0C0C0;
        }

        .myTimetable TD {
          border: 1px solid black;
          padding: 6px;
          text-align: center;
          cursor: pointer;
        }
        .myTimetable TBODY TR TD:first-child {
          background-color: #FF0066;
          font-weight: bold;
        }
        tr:first-child td:first-child { border-top-left-radius: 10px;}
        tr:last-child td:first-child { border-bottom-left-radius: 10px; }
        tr:last-child td:last-child { border-bottom-right-radius: 10px; }
        .break, .lunch {
          background-color: #FF0066 !important;
          font-style: italic;
        }
        .subject {
          font-size: 12pt;
          margin-bottom:4px;
        }
        .room {
          font-size: 10pt;
          font-style: italic;
        }
       .bg-modal {
        width :100%;
        height :100%;
        background-color: rgba(0,0,0,0.8);
        position: absolute;
        top: 0;
        justify-content:  center;
        align-items: center;
        display: none;
       }
       .modal-content {
         width: 500px;
         height :500px;
         background-color: white;
         opacity: 1;
         border-radius: 10px;
         text-align: center;
         padding: 20px;
         position: relative;
       }
       input {
         margin: 7px auto;
       }
       select {
         margin: 7px auto;
       }
       .close {
         position: absolute;
         top:0 ;
         right: 10px;
         font-size: 30px;
         transform: rotate(45deg);
         cursor: pointer;
       }
      .buttons a {
        margin: 50px;
        border-radius: 10px;
      }
      .buttons button {
        border-radius: 10px;
      }
 </style>
<body id="page-top">
  <!-- Modal Section -->
  <div class="bg-modal">
    <div class="modal-content">
      <div class="close">+</div>
        <form class="contact-form" action="/submission/" method="post">
          {% csrf_token %}
           <div class="form-group">
             <label>Jour :</label>
             <select class="custom-select"  name="jour" id="id_jour" >
                <option  selected  >Choisir votre Jour</option>
                {% for jour in Jours %}
                <option value={{ jour.id }}  > {{ jour.nom_Jour }}</option>
                {%endfor%}
            </select>           
           </div>
           <div class="form-group" id="WHT">
            <label>Horaire :</label>
            <select class="custom-select"  name="horaire" id="id_horaire" >
                <option  selected  >Choisir votre crenau</option>
                {% for horaire in all_horaires %}
                <option value={{ horaire.id }}  > {{ horaire.horaire }}</option>
                {%endfor%}
            </select>
           </div>
           <div class="form-group">
             <label>La salle :</label>
             <select class="custom-select"  name="salle" id="id_salles">
                <option selected>Choisir votre Salle</option>
                {% for salleu in all_salles %}
                <option value={{ salleu.id }}>{{ salleu.numero }}</option>
                {% endfor %}
             </select>
           </div>           
           <div class="form-group">
             <label>Le professeur :</label>
             <input type="text" class="form-control" name="Prof" placeholder="Entrez le professeur...">
           </div>
           <div class="form-group">
             <label>La matière :</label>
             <input type="text" class="form-control" name="matière"placeholder="Entrez la matière...">
           </div>
           <div class="buttons">
                  <button type="submit" class="btn btn-dark">Ajouter</button>
          </div>
        </form>         
    </div>

  </div>
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
      <a class="navbar-brand mr-1" href="index.html">Bachelor</a>
      <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
      </button>
      <!-- Navbar Search -->
      <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form>
      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell fa-fw"></i>
            <span class="badge badge-danger">9+</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
          <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-envelope fa-fw"></i>
            <span class="badge badge-danger">7</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">Settings</a>
            <a class="dropdown-item" href="#">Activity Log</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
          </div>
        </li>
      </ul>
    </nav>
    <div id="wrapper">
      <!-- Sidebar -->
      <ul class="sidebar navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="pagesDropdown">
            <h6 class="dropdown-header">Login Screens:</h6>
            <a class="dropdown-item" href="login.html">Login</a>
            <a class="dropdown-item" href="register.html">Register</a>
            <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Other Pages:</h6>
            <a class="dropdown-item" href="404.html">404 Page</a>
            <a class="dropdown-item active" href="blank.html">Blank Page</a>
          </div>
        </li>
      </ul>
      <div id="content-wrapper">
        <div class="container-fluid">
          <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="index.html">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">Blank Page</li>
          </ol>
          <!-- Page Content -->
         <div id ="HTMLtoPDF"> 
          <H1>Emploi du temps </H1>
          <TABLE class="myTimetable" > 
            <THEAD>
              <TR>
                <TH></TH>
                {% for horaire in Horaires %}
                <TH class="Horaires" id={{ horaire.id }}>{{ horaire.horaire }}</TH>
                {% endfor %}
              </TR>
            </THEAD>
            <TBODY> 
              {% for jour in Jours %}
              <TR>
                <TD>{{ jour.nom_Jour }}</TD>
                {% for crenau in Crenaus %}
                {% if crenau.Jour == jour %}
                <form action="supprimer" >
                <TD >
                  <div class="subject">{{ crenau.Matiere }}</div>
                  <div class="room">{{ crenau.salle }}</div>
                  <div class="professeur">{{ crenau.Professeur }}</div>
                </TD>  
                </form>
                {% endif%}          
                {% endfor %}              
              </TR>
              {% endfor %}      
             </TBODY>
            </TABLE>
            </div>
          <div class="buttons">
           <a  href="#" class="btn btn-dark" onclick="HTMLtoPDF()">Download to pdf</a>
           <a  href="#" id="button" class="btn btn-dark">Nouveau crenau</a>
           </div>
        <footer class="sticky-footer">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span> Copyright © Team Bachelor </span>
            </div>
          </div>
        </footer>
      </div>
      <!-- /.content-wrapper -->
    </div>
    <script type="text/javascript">
    document.getElementById('button').addEventListener('click',function(){document.querySelector('.bg-modal').style.display='flex';});
    document.querySelector('.close').addEventListener('click',function(){
      document.querySelector('.bg-modal').style.display='none';});
      </script>

  	<script src=" {% static "js_emploi/jquery.min.js" %} "></script>
    <script src=" {% static "js_emploi/bootstrap.bundle.min.js" %} "></script>
    <!-- Core plugin JavaScript-->
    <script src=" {% static  "js_emploi/jquery.easing.min.js"%} "></script>
    <!-- Custom scripts for all pages-->
    <script src=" {% static  "js_emploi/sb-admin.min.js" %} "></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src=" {% static  "HTML-to-PDF-master/js/jquery-2.1.3.js" %} "></script>
    <script src=" {% static  "HTML-to-PDF-master/js/jspdf.js" %} "></script>
    <script src=" {% static  "HTML-to-PDF-master/js/pdfFromHTML.js" %} "></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script >
        $("#id_salles").change(function ()
         {
          var horaire =  $("#id_horaire").val();
         
          var Jour = $("#id_jour").val();
      
          var Salle_choisie = $("#id_salles").val();
        
          $.ajax(
            {
            url:'/Check',
            method: 'GET',
            data:
            { 
              'Horaire':horaire,
              'Jour' : Jour,
              'Salle_choisie':Salle_choisie,
            },
            success: function (data)
            {   
                if (data.is_not_taken) {
                }else{
                     alert("Cette salle n'est pas libre!");
                }
            }
        });
        });
      </script>
</body>
</html>